// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package override

import (
	"github.com/prog8/sqlc-testdata/pkg"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped pkg.CustomType
}
